#!/usr/bin/env bash
bash "/g/schwab/marco/repos/tem_classification/metab/main.sh" \
    --raw-dir "/g/schwab/marco/projects/trec_metab/datahub_downloads" \
    --sampleinfo "/g/schwab/marco/repos/tem_classification/metab/sampleinfo.tsv" \
    --run-dir "/scratch/rheinnec/ampliseq_4env_test" \
    --work-dir "/scratch/rheinnec/ampliseq_4env_test/work" \
    --results-dir "/scratch/rheinnec/ampliseq_4env_test/ampliseq_pilot_results" \
    --apptainer-cache "/scratch/rheinnec/apptainer_cache" \
    --apptainer-tmp "/scratch/rheinnec/apptainer_tmp" \
    --environmental-samples "4" \
    --control-samples "0" \
    --fw-primer "GTGYCAGCMGCCGCGGTAA" \
    --rv-primer "CCGYCAATTYMTTTRAGTTT" \
    --pipeline-version "2.18.0" \
    --container-profile "apptainer" \
    --binned-quality "2,11,25,37" \
    --max-cpus "16" \
    --max-memory "64.GB" \
    --max-time "48.h" \
    --skip-taxonomy "true" \
    --skip-incomplete "1" \
    --check-gzip "1" 
